name: MaintainableCSS — 以模組化、可擴張與可維護的方式撰寫 CSS。原著：Adam Silver
markdown: kramdown
url: http://intersectiontw.github.io/maintainablecss
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/
description: MaintainableCSS 是以模組化、可擴張與可維護的方式撰寫 CSS。